apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: behavior
resources:
- ../../kubernetes
patches:
- patch: "$patch: delete\napiVersion: monitoring.coreos.com/v1\nkind: ServiceMonitor\n\
    metadata:\n  name: ingestion-api\n  namespace: behavior"
- patch: "$patch: delete\napiVersion: monitoring.coreos.com/v1\nkind: ServiceMonitor\n\
    metadata:\n  name: analytics-api\n  namespace: behavior"
images:
- name: ghcr.io/monoji77/behavior-ingestion-api
  newTag: 69da7cb1d1f66df2a832a14f69e53994684e78f3
- name: ghcr.io/monoji77/behavior-stream-processor
  newTag: 69da7cb1d1f66df2a832a14f69e53994684e78f3
- name: ghcr.io/monoji77/behavior-analytics-api
  newTag: 69da7cb1d1f66df2a832a14f69e53994684e78f3
- name: ghcr.io/monoji77/behavior-dashboard
  newTag: 69da7cb1d1f66df2a832a14f69e53994684e78f3
