apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: behavior
resources:
- ../../kubernetes
patches:
- patch: "$patch: delete\napiVersion: monitoring.coreos.com/v1\nkind: ServiceMonitor\n\
    metadata:\n  name: ingestion-api\n  namespace: behavior"
- patch: "$patch: delete\napiVersion: monitoring.coreos.com/v1\nkind: ServiceMonitor\n\
    metadata:\n  name: analytics-api\n  namespace: behavior"
images:
- name: ghcr.io/monoji77/behavior-ingestion-api
  newTag: 1d6eec9177ffbc74de7c8d55f55b3b150f1a8402
- name: ghcr.io/monoji77/behavior-stream-processor
  newTag: 1d6eec9177ffbc74de7c8d55f55b3b150f1a8402
- name: ghcr.io/monoji77/behavior-analytics-api
  newTag: 1d6eec9177ffbc74de7c8d55f55b3b150f1a8402
