apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: behavior
resources:
- ../../kubernetes
patches:
- patch: "$patch: delete\napiVersion: monitoring.coreos.com/v1\nkind: ServiceMonitor\n\
    metadata:\n  name: ingestion-api\n  namespace: behavior"
- patch: "$patch: delete\napiVersion: monitoring.coreos.com/v1\nkind: ServiceMonitor\n\
    metadata:\n  name: analytics-api\n  namespace: behavior"
images:
- name: ghcr.io/monoji77/behavior-ingestion-api
  newTag: a9a84684771c1769aa502847dff3e676efea2f56
- name: ghcr.io/monoji77/behavior-stream-processor
  newTag: a9a84684771c1769aa502847dff3e676efea2f56
- name: ghcr.io/monoji77/behavior-analytics-api
  newTag: a9a84684771c1769aa502847dff3e676efea2f56
- name: ghcr.io/monoji77/behavior-dashboard
  newTag: a9a84684771c1769aa502847dff3e676efea2f56
