apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: behavior-staging
resources:
- ../../kubernetes
- ../../kubernetes/database
- kafka-topics-job.yaml
- resource-limits.yaml
- priority-class.yaml
patches:
- patch: "$patch: delete\napiVersion: batch/v1\nkind: Job\nmetadata:\n  name: timescaledb-close-events-migration\n\
    \  namespace: behavior"
- patch: "$patch: delete\napiVersion: monitoring.coreos.com/v1\nkind: ServiceMonitor\n\
    metadata:\n  name: ingestion-api\n  namespace: behavior"
- patch: "$patch: delete\napiVersion: monitoring.coreos.com/v1\nkind: ServiceMonitor\n\
    metadata:\n  name: analytics-api\n  namespace: behavior"
- target:
    kind: Service
    name: ingestion-api
  patch: "- op: replace\n  path: /spec/ports/0/port\n  value: 18090"
- target:
    kind: Service
    name: dashboard
  patch: "- op: replace\n  path: /spec/ports/0/port\n  value: 8092"
- target:
    kind: Deployment
    name: ingestion-api
  patch: "- op: add\n  path: /spec/template/spec/containers/0/env/-\n  value:\n  \
    \  name: INGESTION_TOPICS_RAWEVENTS\n    value: staging.app-usage-events.raw.v1"
- target:
    kind: Deployment
    name: stream-processor
  patch: "- op: add\n  path: /spec/template/spec/containers/0/env/-\n  value:\n  \
    \  name: PROCESSOR_TOPICS_RAWEVENTS\n    value: app-usage-events.raw.v1,staging.app-usage-events.raw.v1\n\
    - op: add\n  path: /spec/template/spec/containers/0/env/-\n  value:\n    name:\
    \ PROCESSOR_TOPICS_DEADLETTER\n    value: staging.app-usage-events.dlq.v1\n- op:\
    \ add\n  path: /spec/template/spec/containers/0/env/-\n  value:\n    name: SPRING_KAFKA_CONSUMER_GROUPID\n\
    \    value: raw-event-persistence-staging-v1"
- target:
    kind: Deployment
  patch: "- op: add\n  path: /spec/template/spec/priorityClassName\n  value: behavior-staging-low"
- target:
    kind: StatefulSet
  patch: "- op: add\n  path: /spec/template/spec/priorityClassName\n  value: behavior-staging-low"
images:
- name: ghcr.io/monoji77/behavior-ingestion-api
  newTag: 7174973b3960b4df3e39a3a73b649aef7ea0a850
- name: ghcr.io/monoji77/behavior-stream-processor
  newTag: 7174973b3960b4df3e39a3a73b649aef7ea0a850
- name: ghcr.io/monoji77/behavior-analytics-api
  newTag: 7174973b3960b4df3e39a3a73b649aef7ea0a850
- name: ghcr.io/monoji77/behavior-dashboard
  newTag: 7174973b3960b4df3e39a3a73b649aef7ea0a850
