spring:
  application:
    name: ingestion-api
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
      properties:
        "[spring.json.add.type.headers]": false
  jackson:
    deserialization:
      fail-on-unknown-properties: true

server:
  port: ${SERVER_PORT:8080}

management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

ingestion:
  collector-token: ${INGESTION_COLLECTOR_TOKEN}
  topics:
    raw-events: app-usage-events.raw.v1